# render.yaml
services:
  - type: web
    name: ml_project_sudhanshu
    env: python
    # The Python runtime version you want
    pythonVersion: "3.10.13"
    # Entry point of your app
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    plan: free